server:
  error:
    include-message: always
    include-exception: on
  port: 8079

spring:
  main:
    banner-mode: off

  datasource:
    hikari:
      connection-timeout: 1000

springdoc:
  swagger-ui:
    path: /swagger-ui.html

#telegram:

#  Telegram bot API-token
#  token: 612543674:AAGWTokenTokenTokenRYEYZ_DRTokenPRa
